services:
  elasticsearch:
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    ports:
      - "127.0.0.1:9200:9200"
    environment:
      - ES_JAVA_OPTS=${ES_JAVA_OPTS}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - discovery.type=single-node
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - network.host=0.0.0.0
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - ./volumes/elasticsearch-data:/usr/share/elasticsearch/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  setup-elasticsearch:
    image: alpine:3.18
    depends_on:
      - elasticsearch
    entrypoint: ["/bin/sh", "-c", "apk add --no-cache curl && /opt/change_kibana_password.sh"]
    volumes:
      - ./scripts/change_kibana_password.sh:/opt/change_kibana_password.sh
    environment:
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - KIBANA_SYSTEM_PASSWORD=${KIBANA_SYSTEM_PASSWORD}

  kibana:
    restart: always
    image: docker.elastic.co/kibana/kibana:8.15.0
    ports:
      - "127.0.0.1:5601:5601"
    environment:
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_SYSTEM_PASSWORD}
      - KIBANA_LOG_LEVEL=${KIBANA_LOG_LEVEL}
      - XPACK_SECURITY_ENCRYPTION_KEY=${XPACK_SECURITY_ENCRYPTION_KEY}
      - XPACK_SAVED_OBJECTS_ENCRYPTION_KEY=${XPACK_SAVED_OBJECTS_ENCRYPTION_KEY}
      - XPACK_REPORTING_ENCRYPTION_KEY=${XPACK_REPORTING_ENCRYPTION_KEY}
      - SERVER_PUBLIC_BASE_URL=${SERVER_PUBLIC_BASE_URL}
      - SERVER_NAME=kibana
      - SERVER_HOST=0.0.0.0
    depends_on:
      - setup-elasticsearch
    volumes:
      - ./cnf/kibana.yml:/usr/share/kibana/config/kibana.yml
      - ./volumes/kibana-data:/usr/share/kibana/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  caddy:
    image: caddy:2.8.4
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./cnf/Caddyfile:/etc/caddy/Caddyfile
      - ./volumes/caddy-data:/data
      - ./volumes/caddy-config:/config
    environment:
      - EMAIL=${DOMAIN_EMAIL}
      - ACME_AGREE=true
      - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST}
      - KIBANA_HOST=${KIBANA_HOST}
    depends_on:
      - kibana
      - elasticsearch
